### ISSUE TITLE
[Doc Request]: 针对 Google 和 Bing SEO 优化

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao.Docs#116]
### 想要的文档

- [x] 为全部页面添加 description 属性
- [x] 为重要页面添加合适的 banner image

**Comment by Mister-Hope** [comment]
这个原则上来讲，你在每篇文章的前面做一个合理的描述，然后添加一个 more 注释，然后再开始二级标题就可以了

**Comment by Mister-Hope** [comment]
我觉得部分界面可能是你自己手动设置一个描述会更好一点，但大部分页面按照我说的去做就没有问题

**Comment by Masterain98** [comment]
> 这个原则上来讲，你在每篇文章的前面做一个合理的描述，然后添加一个 more 注释，然后再开始二级标题就可以了

![image](https://github.com/DGP-Studio/Snap.Hutao.Docs/assets/10614984/57dcdbf9-9b5e-4d00-8a64-2f8dae37b706)

这个比较怪，像是主页，之前谷歌就会抓取最前面的文字。但是对于一些文章，比如 [My Character](https://hut.ao/en/features/character-data.html) 显示出来的内容是在文章中间，而不是第一段话。

---

> 我觉得部分界面可能是你自己手动设置一个描述会更好一点，但大部分页面按照我说的去做就没有问题

页面数量其实不算多，简介也不需要写多长，一两句话而已。所以还是给值得加的页面都加一下吧。

**Comment by Mister-Hope** [comment]
你只要用more注释去给页面设置一段摘要，那么seo插件会自动用这个摘要生成一个描述。 不是说搜索引擎去默认抓第1个二级标题之前的文字，而是插件自动帮你生成了一个描述。

**Comment by Mister-Hope** [comment]
我并不觉得手动维护每一篇页面的描述是一个好主意

**Comment by Masterain98** [comment]
> 你只要用more注释去给页面设置一段摘要

这个有更详细的解释吗？我在 SEO 插件页面和 theme-hope 文档里都没搜到这个解释（theme-hope的文档搜索出来全是 update-log 文章里的内容，从 crwaler 里排除掉可能会有助于搜索）

**Comment by Masterain98** [comment]
@Mister-Hope 我按照 theme-hope 的文档抄了一份，但并没有用。
![image](https://github.com/DGP-Studio/Snap.Hutao.Docs/assets/10614984/60ea09f6-30ef-476a-8479-c639eea79cf3)
![image](https://github.com/DGP-Studio/Snap.Hutao.Docs/assets/10614984/fa5c3e1d-9bec-4164-8506-71b22376708b)

---
theme-hope 的文档中实际上也没有生成 description

![image](https://github.com/DGP-Studio/Snap.Hutao.Docs/assets/10614984/17c2b5bb-2f98-4a09-a2b3-8dd055dbecec)
![image](https://github.com/DGP-Studio/Snap.Hutao.Docs/assets/10614984/b9372498-ec54-45a9-bd5b-f920963594fd)

**Comment by Mister-Hope** [comment]
我回头看一下

**Comment by Mister-Hope** [comment]
seo那个问题修了，等新版就行
