### ISSUE TITLE
[Feat]: 胡桃网站搜索时增加搜索框宽度并显示详情

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao.Docs#119]
### 背景与动机

<img width="511" alt="e4d0e59681f1cf4d048459835b495771" src="https://github.com/DGP-Studio/Snap.Hutao/assets/63829496/2ad18fc5-12c8-4b4f-96fe-8fe1fff2941a">

如图所示，倒一和倒二显示的内容完全一致，但实际指向的链接是不同的，希望增加搜索框宽度以显示详情的小标题

### 想要实现或优化的功能

优化网站的搜索功能，显示详细小标题

**Comment by BTMuli** [comment]
> 希望增加搜索框宽度以显示详情的小标题

事实上，增加宽度也不会把省略的内容给显示全，搜索结果的展现依赖于插件 [docsearch](https://ecosystem.vuejs.press/zh/plugins/docsearch.html#docsearch) 的实现，

而 docsreach 对于搜索结果组件直接继承的 algolia 的 `@docsearch/react`，

然后翻看后者[源码](https://github.com/algolia/docsearch/blob/main/packages/docsearch-react/src/Results.tsx)，拿的数据是 `_snippetResult.content.value` 而非上级的 `content`，其内容就是你审查元素的那个带 `<mark>` 的，没有省略

所以这个超出了文档站的范围，建议去 [上游](https://github.com/vuepress/ecosystem/tree/main/plugins/plugin-docsearch) 提 issue 反馈

**Comment by Mikachu2333** [comment]
> 这个超出了文档站的范围，建议去 [上游](https://github.com/vuepress/ecosystem/tree/main/plugins/plugin-docsearch) 提 issue 反馈

收到，后几天抽个空去反馈然后旧关闭本issues

**Comment by Mikachu2333** [comment]
根据 https://github.com/vuepress/ecosystem/issues/109#issuecomment-2082663357 不是这个上游的错…… 得继续往上找……

**Comment by Mikachu2333** [comment]
So, what can i do…… 对html类的语言一窍不通……

**Comment by Mister-Hope** [comment]
You can open an issue at docsearch.. Tell them you are using the default configuration, and want these text to be longer
