### ISSUE TITLE
[Doc Request]: 成就管理中缺少成就来源查看

### ISSUE THREAD

**Issue by CLXiao-1029** [DGP-Studio/Snap.Hutao.Docs#122]
### 想要的文档

在未完成的成就被点击时或被右键点击时，可以告诉使用者这个成就该如何获得~谢谢！！

### 需要更新的文档链接

https://hut.ao/zh/features/achievements.html

**Comment by Masterain98** [comment]
这是程序文档，不是原神攻略文档

**Comment by CLXiao-1029** [comment]
我发错位置了，已经转成提交了新的功能需求~
