### ISSUE TITLE
[Doc Request]: 增加导入祈愿记录的简单原理

### ISSUE THREAD

**Issue by Mikachu2333** [DGP-Studio/Snap.Hutao.Docs#125]
### 想要的文档

https://github.com/DGP-Studio/Snap.Hutao/issues/1572#issuecomment-2077316819

详见群内讨论，因没法上传图像导致不能更新

### 需要更新的文档链接

https://hut.ao/zh/features/wish-export.html

**Comment by BTMuli** [comment]
> 因没法上传图像导致不能更新

？

**Comment by Mikachu2333** [comment]
> > 因没法上传图像导致不能更新
> 
> ？

都是用的阿里做的图床啊，没有用其他图床的情况，手头没有阿里的资源……

**Comment by Masterain98** [comment]
直接开 PR 吧，图片可以放在 `docs/.vuepress/public/images` 目录里
