### ISSUE TITLE
哈希值说是有错无法安装

### ISSUE THREAD

**Issue by xixi3535** [DGP-Studio/Snap.Hutao.Docs#131]
### 想要的文档

![QQ图片20240615212229](https://github.com/DGP-Studio/Snap.Hutao.Docs/assets/172910572/2e99960f-4943-41b3-b968-a557a8e5dedd)
![QQ图片20240615212239](https://github.com/DGP-Studio/Snap.Hutao.Docs/assets/172910572/596d67e5-6ceb-40da-8f16-309678b4594a)
![QQ图片20240615212539](https://github.com/DGP-Studio/Snap.Hutao.Docs/assets/172910572/08843b09-e7f4-4c90-b551-cdffe901d623)

**Comment by qhy040404** [comment]
你把issue开哪来了

**Comment by xixi3535** [comment]
不知道啊，我就直接启动，下一半突然停了，重下后就变这样了
