### ISSUE TITLE
I want to add another language to your document.

### ISSUE THREAD

**Issue by prpjzz** [DGP-Studio/Snap.Hutao.Docs#49]
As the title says, I want to add another language, in addition to English and Chinese, but I have a problem as in the picture.
![image](https://github.com/DGP-Studio/Snap.Hutao.Docs/assets/89702898/1171db72-acc2-4abd-9244-c6ab1e0b4c3e)

I don't have much experience in multi-lingual web-making, so I hope you can help me with this. Thank you.~

**Comment by Masterain98** [comment]
You can simply add new markdown documents under `docs/{your_language_code}` folder and start a new PR. Then I can add commit to handle the software settings.

**Comment by Masterain98** [comment]
https://github.com/DGP-Studio/Snap.Hutao/issues/909
