### ISSUE TITLE
胡桃软件内会提示“InvalidOperationException 在查找必要的模块时遇到问题：无法读取任何模块，可能是保护驱动已经加载完成”。

### ISSUE THREAD

**Issue by Autism0821** [DGP-Studio/Snap.Hutao.Docs#58]
胡桃软件内会提示“InvalidOperationException 在查找必要的模块时遇到问题：无法读取任何模块，可能是保护驱动已经加载完成”。
每天开机启动游戏就会有，第二次就不会出现了。

**Comment by Lightczx** [comment]
intended behavior
