### ISSUE TITLE
无法通过Snap.Hutao启动原神

### ISSUE THREAD

**Issue by MrOooooorange** [DGP-Studio/Snap.Hutao.Docs#8]
游戏路径设置原神文件夹中的launcher文件后点击启动，无反应，并弹窗提示“游戏路径不正确，前往设置更改游戏路径。”

**Comment by AdminRoc** [comment]
![image](https://user-images.githubusercontent.com/96916320/206165549-146fc76d-b14c-4bad-a421-a09b40b24347.png)
bad issue
