### ISSUE TITLE
我希望提供一个可以快速!!!查看角色好感度的功能

### ISSUE THREAD

**Issue by QiFenQAQ** [DGP-Studio/Snap.Hutao.Docs#96]
### 想要的文档

RT,这样在刷好感度的时候就不会不知道刷谁了

**Comment by QiFenQAQ** [comment]
为什么在没有回复的情况关闭我的建议,是因为你们觉得没有意义吗?
&nbsp;


该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月5日(星期五) 下午4:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DGP-Studio/Snap.Hutao.Docs] 我希望提供一个可以快速!!!查看角色好感度的功能 (Issue #96)





 
Closed #96 as not planned.

**Comment by Masterain98** [comment]
![image](https://github.com/DGP-Studio/Snap.Hutao.Docs/assets/10614984/32051a83-adca-43de-82f5-a48098e28e68)
